// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvqaAAPNfuTiLg5SKAh0zbk-fjsiea7Y',
    appId: '1:240438237901:web:54c157857271d57be8a784',
    messagingSenderId: '240438237901',
    projectId: 'hajjwarehouses',
    authDomain: 'hajjwarehouses.firebaseapp.com',
    storageBucket: 'hajjwarehouses.firebasestorage.app',
    measurementId: 'G-6ZTKXZFDR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9WusTB5MzyPqMfvO5yJQtBMI7Xc3w0M',
    appId: '1:240438237901:android:8cdeb3bdedd6ed60e8a784',
    messagingSenderId: '240438237901',
    projectId: 'hajjwarehouses',
    storageBucket: 'hajjwarehouses.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3tj_GUnCHbybRRInBBCDVtNsQQOe4fg',
    appId: '1:240438237901:ios:949308c949775b0de8a784',
    messagingSenderId: '240438237901',
    projectId: 'hajjwarehouses',
    storageBucket: 'hajjwarehouses.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8hNNIE1bvwJVlSXH4qrvRKtC3lwzK3g',
    appId: '1:185797542866:ios:0f7a07b8cf64a3ccce3e0b',
    messagingSenderId: '185797542866',
    projectId: 'project-zac',
    storageBucket: 'project-zac.firebasestorage.app',
    iosBundleId: 'com.example.projectZacApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSUh9waZnuRDZ2-CP1FCv0C-mDXD6TXKU',
    appId: '1:185797542866:web:383273bb1edb09fbce3e0b',
    messagingSenderId: '185797542866',
    projectId: 'project-zac',
    authDomain: 'project-zac.firebaseapp.com',
    storageBucket: 'project-zac.firebasestorage.app',
    measurementId: 'G-LSX1J7ER38',
  );
}